
[package]
name = "batsmt-stubs"
version = "0.1.0"
authors = ["Simon Cruanes"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]

ocaml = "0.5"
bit-set = "0.5.0"
fxhash = "0.2"
#batsmt = "*"
batsmt-core = { git="https://github.com/AestheticIntegration/batsmt", rev="b05fbf2c92f3c3ec851d70853e0330bf29930fa9" }
batsmt-cc = { git="https://github.com/AestheticIntegration/batsmt", rev="b05fbf2c92f3c3ec851d70853e0330bf29930fa9" }
batsmt-hast = { git="https://github.com/AestheticIntegration/batsmt", rev="b05fbf2c92f3c3ec851d70853e0330bf29930fa9" }
batsmt-theory = { git="https://github.com/AestheticIntegration/batsmt", rev="b05fbf2c92f3c3ec851d70853e0330bf29930fa9" }
batsmt-solver = { git="https://github.com/AestheticIntegration/batsmt", rev="b05fbf2c92f3c3ec851d70853e0330bf29930fa9" }

[workspace]

