
[package]
name = "batsmt-stubs"
version = "0.1.0"
authors = ["Simon Cruanes"]
edition = "2018"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]

ocaml = "0.5"
bit-set = "0.5.0"
fxhash = "0.2"
#batsmt = "*"
batsmt-core = { git="https://github.com/AestheticIntegration/batsmt",   rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }
batsmt-cc = { git="https://github.com/AestheticIntegration/batsmt",     rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }
batsmt-hast = { git="https://github.com/AestheticIntegration/batsmt",   rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }
batsmt-theory = { git="https://github.com/AestheticIntegration/batsmt", rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }
batsmt-solver = { git="https://github.com/AestheticIntegration/batsmt", rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }
batsmt-pretty = { git="https://github.com/AestheticIntegration/batsmt", rev="eaa342bf4c0f44ac09748f7cc986f1823f2aa33c" }

[workspace]

